language: php
php:
  - '5.6'
  - '7.0'
  - 'nightly'
  - 'hhvm'

before_script:
  - echo "extension = sockets.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_install:
  - composer self-update

install:
  - composer --prefer-source -n install
